 package uninit.genesis.app.theme.builtin

// catppuccin.mocha.* is a theme
val AllThemes = listOf(
    DefaultMaterialTheme,
    Catppuccin.Latte.Lavender,
    Catppuccin.Latte.Blue,
    Catppuccin.Latte.Sapphire,
    Catppuccin.Latte.Sky,
    Catppuccin.Latte.Teal,
    Catppuccin.Latte.Green,
    Catppuccin.Latte.Yellow,
    Catppuccin.Latte.Peach,
    Catppuccin.Latte.Maroon,
    Catppuccin.Latte.Red,
    Catppuccin.Latte.Mauve,
    Catppuccin.Latte.Pink,
    Catppuccin.Latte.Flamingo,
    Catppuccin.Latte.Rosewater,
    Catppuccin.Frappe.Lavender,
    Catppuccin.Frappe.Blue,
    Catppuccin.Frappe.Sapphire,
    Catppuccin.Frappe.Sky,
    Catppuccin.Frappe.Teal,
    Catppuccin.Frappe.Green,
    Catppuccin.Frappe.Yellow,
    Catppuccin.Frappe.Peach,
    Catppuccin.Frappe.Maroon,
    Catppuccin.Frappe.Red,
    Catppuccin.Frappe.Mauve,
    Catppuccin.Frappe.Pink,
    Catppuccin.Frappe.Flamingo,
    Catppuccin.Frappe.Rosewater,
    Catppuccin.Macchiato.Lavender,
    Catppuccin.Macchiato.Blue,
    Catppuccin.Macchiato.Sapphire,
    Catppuccin.Macchiato.Sky,
    Catppuccin.Macchiato.Teal,
    Catppuccin.Macchiato.Green,
    Catppuccin.Macchiato.Yellow,
    Catppuccin.Macchiato.Peach,
    Catppuccin.Macchiato.Maroon,
    Catppuccin.Macchiato.Red,
    Catppuccin.Macchiato.Mauve,
    Catppuccin.Macchiato.Pink,
    Catppuccin.Macchiato.Flamingo,
    Catppuccin.Macchiato.Rosewater
)